### PR TITLE
Basic documentation structure and YAML input spec

### LINKED ISSUE #48: Document the input spec in Markdown
We don't have a documentation strategy for this project yet, but I think it would be good for us to start writing down some important things while they're fresh in our heads. To me, the input specification is the most important thing for us to document at the moment, so I'll put together a Markdown file for it that we can add to a `docs/` folder. When we decide on a more formal documentation approach, we can deploy such Markdown files to a GitHub Pages environment using an appropriate site generator.

### PR DESCRIPTION
**Pull request by jeff-cohere**
This PR is a start on our documentation structure using an E3SM-approved approach. I've made provisions for a User Guide and a Developer Guide, and I've started documenting RDycore's YAML input format.

Closes #48

### CODE REVIEW

**Comment by bishtgautam** [comment]
@jeff-cohere Can we borrow the infrastructure from the following recent E3SM PR https://github.com/E3SM-Project/E3SM/pull/5951 that shows a review of the documentation in any PR that is opened e.g. https://github.com/E3SM-Project/E3SM/pull/5980#issuecomment-1756027489?

**Comment by jeff-cohere** [comment]
Sure, I think I can patch that in.

**Comment by bishtgautam** [comment]
Also please include the following patch https://github.com/E3SM-Project/E3SM/pull/5961/files

**Comment by jeff-cohere** [comment]
I'm basing the specification for `initial_conditions` and `sources` (and probably also `surface_composition`) on a proposal in #96, in which I suggest removing the `domain` option for reading from files in favor of specifying the file to read on a per condition basis. That seems simpler and possibly more flexible to me, though I think it deserves some discussion.

**Review by bishtgautam — APPROVED** [review]

**Pull request merged**
