### PR TITLE
Reordered parsing of ensemble members and math expressions to fix an issue.

### LINKED ISSUE #220: Ensemble capability is broken
```
cd build/driver/tests/swe_roe
$PETSC_DIR/$PETSC_ARCH/bin/mpiexec -n 5 ../../rdycore ex2b-ensemble.yaml
DETAIL: ==========================================================
DETAIL: RDycore (input read from ex2b-ensemble.yaml)
DETAIL: ==========================================================
DETAIL: Ensemble:
DETAIL:   Size: 5
DETAIL: Physics:
DETAIL:   Flow:
DETAIL:   Sediment model: disabled
DETAIL:   Salinity model: disabled
DETAIL: Numerics:
DETAIL:   Spatial discretization: finite volume (FV)
DETAIL:   Temporal discretization: forward euler
DETAIL:   Riemann solver: roe
DETAIL: Time:
DETAIL:   Final time: 0.005 days
DETAIL: Logging:
DETAIL:   Primary log file: <stdout>
DETAIL: Checkpoint:
DETAIL:   File format: binary
DETAIL:   interval: 100
DETAIL: Restart:
DETAIL:   (disabled)
[4]PETSC ERROR: ------------------------------------------------------------------------
[4]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[4]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[4]PETSC ERROR: or see https://petsc.org/release/faq/#valgrind and https://petsc.org/release/faq/
[4]PETSC ERROR: ---------------------  Stack Frames ------------------------------------
[4]PETSC ERROR: The line numbers in the error traceback are not always exact.
[4]PETSC ERROR: #1 InitMaterials() at /Users/bish218/projects/rdycore/rdycore/src/rdysetup.c:525
[4]PETSC ERROR: #2 RDySetup() at /Users/bish218/projects/rdycore/rdycore/src/rdysetup.c:961
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see https://petsc.org/release/faq/#valgrind and https://petsc.org/release/faq/
[0]PETSC ERROR: ---------------------  Stack Frames ------------------------------------
[0]PETSC ERROR: The line numbers in the error traceback are not always exact.
[0]PETSC ERROR: #1 InitMaterials() at /Users/bish218/projects/rdycore/rdycore/src/rdysetup.c:525
[0]PETSC ERROR: #2 RDySetup() at /Users/bish218/projects/rdycore/rdycore/src/rdysetup.c:961
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
  Proc: [[3820,1],0]
  Errorcode: 59

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
prterun has exited due to process rank 0 with PID 0 on node WD86346 calling
"abort". This may have caused other processes in the application to be
terminated by signals sent by prterun (as reported here).
--------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by jeff-cohere**
Also: improved input validation for material properties. This PR should be merged after #222.

Fixes #220

### CODE REVIEW

**Comment by jeff-cohere** [comment]
The checks on this PR will run once #222 is merged. The tests pass on my workstation.

**Review by bishtgautam — APPROVED** [review]
I verified this works. Thanks.

Btw, why did this wasn't failing on the Github Actions? Are we missing a test for it?

**Comment by jeff-cohere** [comment]
> Btw, why did this wasn't failing on the Github Actions? Are we missing a test for it?

I think so, yeah. The GitHub Actions test runners have at most 2 processes available, so we have to oversubscribe them to get to 5 processes, and I just haven't put that in yet. Maybe it's time to do that.

**Comment by jeff-cohere** [comment]
I suspect the reason we haven't done this yet is that we can't necessarily figure out from PETSc how to oversubscribe processors any given MPI implementation. I'm not sure how much of an issue this is, but it may affect running tests on the bigger machines.

**Comment by jeff-cohere** [comment]
I ended up reducing the number of ensemble members to 2 in that test so it works in our environment. It should be clear how to extend it to any number from the example input, though. Does that work?

**Comment by bishtgautam** [comment]
Using two ensembles is good.

**Pull request merged**
