### PR TITLE
Updates to support PETSc v3.22.0

### LINKED ISSUE #221: Update PETSc docker to v3.22.0
We need @markadams's fix to `VecCopy` for GPUs, which is included in PETSc v3.22.0.

@jeff-cohere I have a branch where I'm updating the PETSc installation setting for Perlmutter and Frontier. I will open a PR when the branch is ready and then you can add a new commit in it that updates the PETSc Docker image.

### PR DESCRIPTION
**Pull request by bishtgautam**
- PETSc installations have been updated on:
  - Frontier
  - Perlmutter 
- Scripts and documentation have been updated on indicate the latest PETSc version.

Fixes #221

### CODE REVIEW

**Comment by bishtgautam** [comment]
@jonbob On NERSC, could you please test out this branch with the updated E3SM-RDycore coupling instructions following the two instructions?
 - CPU run: https://rdycore.github.io/RDycore/pr-preview/pr-222/user/example-cases/harvey-flooding/ocean-bc/index.html#example-for-perlmutter-cpu-nodes
 - GPU run https://rdycore.github.io/RDycore/pr-preview/pr-222/user/example-cases/harvey-flooding/ocean-bc/index.html#example-for-perlmutter-gpu-nodes

**Comment by jonbob** [comment]
@bishtgautam -- yes, I'll do that today and post results here

**Comment by jonbob** [comment]
@bishtgautam - I'm running into problems. This is what I've done:
````
git clone git@github.com:rdycore/e3sm rdycore-e3sm
cd rdycore-e3sm/
git checkout rdycore/mosart-rdycore/d4ca7d0606-2024-10-02 
git submodule update --init --recursive
cd externals/rdycore/
git submodule update --init --recursive
cd docs/user/example-cases/harvey-flooding/ocean-bc/
./setup_harvey_flooding_ocean_bc.sh  --mach pm-cpu -N 1 --project m4267 --rdycore-dir /pscratch/sd/j/jonbob/rdycore-e3sm/externals/rdycore/
````
It didn't seem to find petsc -- I got this error message:
````
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Will source the following module file and set the following PETSc settings

  source /pscratch/sd/j/jonbob/rdycore-e3sm/externals/rdycore/config/modules.pm-cpu.gnu
  export PETSC_DIR=/global/cfs/projectdirs/m4267/petsc/petsc_v3.22.0/
  export PETSC_ARCH=pm-cpu-hdf5_1_14_3-opt-64bit-gcc-11-2-0-v3.22.0

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Unloading the cpe module is insufficient to restore the system defaults.
Please run 'source /opt/cray/pe/cpe/23.12/restore_lmod_system_defaults.[csh|sh]'.

The following have been reloaded with a version change:
  1) gcc/12.2.0 => gcc/11.2.0


Lmod is automatically replacing "craype-accel-nvidia80" with "craype-accel-host".


The following have been reloaded with a version change:
  1) craype/2.7.30 => craype/2.7.20

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
The following expected RDycore build directory not found:/pscratch/sd/j/jonbob/rdycore-e3sm/externals/rdycore//build-pm-cpu-hdf5_1_14_3-opt-64bit-gcc-11-2-0-v3.22.0 
So, attempting to build RDycore.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Cray Programming Environment 2.7.20 C
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/cray/pe/craype/2.7.20/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Cray Programming Environment 2.7.20 CXX
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/cray/pe/craype/2.7.20/bin/CC - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 11.2.0
-- Cray Programming Environment 2.7.20 Fortran
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/cray/pe/craype/2.7.20/bin/ftn - skipped
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'PETSc'
--   No package 'PETSc' found
CMake Error at /global/common/software/nersc/pm-2022q4/spack/linux-sles15-zen/cmake-3.24.3-k5msymx/share/cmake-3.24/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /global/common/software/nersc/pm-2022q4/spack/linux-sles15-zen/cmake-3.24.3-k5msymx/share/cmake-3.24/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:29 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/pscratch/sd/j/jonbob/rdycore-e3sm/externals/rdycore/build-pm-cpu-hdf5_1_14_3-opt-64bit-gcc-11-2-0-v3.22.0/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'install'.  Stop.
````

**Comment by jeff-cohere** [comment]
Hi @jonbob. Can you retry with this branch? (`bishtgautam/petsc-v3.22.0`) Or is the branch you used (`rdycore/mosart-rdycore/d4ca7d0606-2024-10-02`) a subbranch?

**Comment by jonbob** [comment]
@jeff-cohere - when I looked at the RDycore branch I ended up with, I thought it said bishtgautam/petsc-v3.22.0. But I'll check again

**Comment by jonbob** [comment]
@jeff-cohere - I did not have that branch checked out. I had looked at the git log and it said "Updates PETSc to v3.22.0 on Perlmutter" but wasn't on that branch. So now I've checked it out and updated the submodules, but I'm still getting the same result

**Comment by jeff-cohere** [comment]
Thanks for trying again! This is odd, since the `pkg-config` file RDycore looks for (`PETSc.pc`) seems to be installed in the right location (`${PETSC_DIR}/${PETSC_ARCH}/lib/pkgconfig`, see [here](https://github.com/RDycore/RDycore/blob/bishtgautam/petsc-v3.22.0/CMakeLists.txt#L24) on Perlmutter:

```
> ls /global/cfs/projectdirs/m4267/petsc/petsc_v3.22.0/pm-cpu-hdf5_1_14_3-opt-64bit-gcc-11-2-0-v3.22.0/lib/pkgconfig/
ceed.pc  muparser.pc  petsc.pc	PETSc.pc  scalapack.pc	zlib.pc
```

@bishtgautam is at an all-day meeting, but maybe he can comment on whether he's seen this issue before when he's free.

**Comment by jonbob** [comment]
@jeff-cohere -- but we're not loading the module? At least when I looked I didn't see PETSc in the list, but maybe it's not required. I had worked with PETSc on an mpas-ocean branch a few years ago and it didn't seem easy to get included in the build

**Comment by knepley** [comment]
@jonbob We are not loading a PETSc module because we are building it ourselves

**Comment by bishtgautam** [comment]
@jonbob I did indeed forget to update the RDycore submodule within the `rdycore/mosart-rdycore/d4ca7d0606-2024-10-02`. I have updated the branch to include newer commits in RDycore.

**Comment by bishtgautam** [comment]
@jonbob, @donghuix caught my mistake in that I had previously provided links to RDycore-alone simulation instructions instead of E3SM-RDycore simulation instructions. Please try the instructions on https://rdycore.github.io/RDycore/pr-preview/pr-222/user/example-cases/e3sm-cases/harvey-flooding/e3sm_harvey.html

**Comment by jonbob** [comment]
@bishtgautam -- I think I needed to be added to the m4267 group. Otherwise the build fails with permissions problems for the petsc files

**Review by jeff-cohere — APPROVED** [review]

**Pull request merged**
