### PR TITLE
Removes setting the number of quadrature points

### LINKED ISSUE #81: ceed tests failing
I just got latest the versions of PETSc and RDycore and when I tried to run the tests for RDycore the following test failed.	 
         11 - swe_roe_ex2b_c_np_1_ceed (Failed)
	 12 - swe_roe_ex2b_f90_np_1_ceed (Failed)
	 18 - swe_roe_ex2b_f90_np_2_ceed (Failed)
	 23 - swe_roe_ex2b_cgns_c_np_1_ceed (Failed)
	 24 - swe_roe_ex2b_cgns_f90_np_1_ceed (Failed)
	 29 - swe_roe_ex2b_cgns_c_np_2_ceed (Failed)
	 30 - swe_roe_ex2b_cgns_f90_np_2_ceed (Failed)
	 35 - swe_roe_ex2b_ic_file_c_np_1_ceed (Failed)
	 36 - swe_roe_ex2b_ic_file_f90_np_1_ceed (Failed)
	 41 - swe_roe_ex2b_ic_file_c_np_2_ceed (Failed)
	 42 - swe_roe_ex2b_ic_file_f90_np_2_ceed (Failed)
	 47 - swe_roe_four_mounds_c_np_1_ceed (Failed)
	 48 - swe_roe_four_mounds_f90_np_1_ceed (Failed)
	 53 - swe_roe_four_mounds_c_np_2_ceed (Failed)
	 54 - swe_roe_four_mounds_f90_np_2_ceed (Failed)
output from cmake:
cmake ../RDycore/ -DCMAKE_INSTALL_PREFIX=~/rdycore/debug -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The Fortran compiler identification is GNU 11.4.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- petsc_lib_dir /home/arcowie/petsc/arch-linux-rdycore-debug/lib
-- Recognized PETSc install with single library for all packages
-- Performing Test MULTIPASS_TEST_1_petsc_works_minimal
-- Performing Test MULTIPASS_TEST_1_petsc_works_minimal - Success
-- Minimal PETSc includes and libraries work.  This probably means we are building with shared libs.
-- Found PETSc: /home/arcowie/petsc/arch-linux-rdycore-debug/include;/home/arcowie/petsc/include (found version "3.19.5.99") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'ceed'
--   Found ceed, version 0.11.0
-- Configuring RDycore (Debug)
-- Generating project files in build directory: /home/arcowie/rdycore/build
-- C compiler is /home/arcowie/petsc/arch-linux-rdycore-debug/bin/mpicc (GNU 11.4.0)
-- Fortran compiler is /usr/bin/gfortran (GNU 11.4.0)
-- Configuring RDycore v0.1.0
-- Installation prefix is /home/arcowie/rdycore/debug
-- Found Patch: /usr/bin/patch  
-- Valgrind found. Enabling `make memcheck`
-- Configuring done
-- Generating done
-- Build files have been written to: /home/arcowie/rdycore/build

I am attaching the LastTest.Log, nd my petsc configure.log
[LastTest.log](https://github.com/RDycore/RDycore/files/12563783/LastTest.log)
[configure.log](https://github.com/RDycore/RDycore/files/12563802/configure.log)

### PR DESCRIPTION
**Pull request by bishtgautam**
The call to CeedOperatorSetNumQuadraturePoints is not needed.

Fixes #81

### CODE REVIEW

**Comment by bishtgautam** [comment]
@jeff-cohere This PR requires us to update the PETSc docker. Can you please update the PETSc docker to use PETSc hash [b3128c15e0ede1c14e9cb30fdd8d296dd7c78e34](https://gitlab.com/petsc/petsc/-/commit/b3128c15e0ede1c14e9cb30fdd8d296dd7c78e34)? Thanks.

**Comment by jeff-cohere** [comment]
Ready for your review, @arcowie .

**Comment by jeff-cohere** [comment]
@bishtgautam , should we merge this? Seems like it would be good for us to use the more recent version of PETSc from here on (though I suspect we'll be updating PETSc pretty frequently in the coming months).

**Comment by bishtgautam** [comment]
Yes, let's merge this. Could you approve and merge it?

**Pull request merged**
